package id.go.bkn.sscn.persistence.entities;

// Generated Aug 14, 2013 11:26:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * RefLokasi generated by hbm2java
 */
@Entity
@Table(name = "INSTANSI_THK2", catalog = "dbseleksicpns")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class InstansiThk2 implements java.io.Serializable {

	private String kode;
	private PropThk2 prop;
	private String nama;
	private String flag;

	public InstansiThk2() {
	}

	@Id
	@Column(name = "KD_INSKER", unique = true, nullable = false, length = 4)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@ManyToOne(fetch = FetchType.LAZY)	
	@JoinColumn(name = "KD_PROP", nullable = false)	
	public PropThk2 getProp() {
		return this.prop;
	}

	public void setProp(PropThk2 prop) {
		this.prop = prop;
	}

	@Column(name = "nama", length = 200)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "flag", length = 1)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
