package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RefPnsId generated by hbm2java
 */
@Embeddable
public class RefPnsId implements java.io.Serializable {

	private String nip;
	private String nama;
	private String instansi;
	private String status;

	public RefPnsId() {
	}

	public RefPnsId(String nip, String nama, String instansi, String status) {
		this.nip = nip;
		this.nama = nama;
		this.instansi = instansi;
		this.status = status;
	}

	@Column(name = "NIP", unique = true, nullable = false, length = 18)
	public String getNip() {
		return this.nip;
	}

	public void setNip(String nip) {
		this.nip = nip;
	}

	@Column(name = "NAMA", nullable = false, length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "INSTANSI", nullable = false, length = 4)
	public String getInstansi() {
		return this.instansi;
	}

	public void setInstansi(String instansi) {
		this.instansi = instansi;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RefPnsId))
			return false;
		RefPnsId castOther = (RefPnsId) other;

		return ((this.getNip() == castOther.getNip()) || (this.getNip() != null
				&& castOther.getNip() != null && this.getNip().equals(
				castOther.getNip())))
				&& ((this.getNama() == castOther.getNama()) || (this.getNama() != null
						&& castOther.getNama() != null && this.getNama()
						.equals(castOther.getNama())))
				&& ((this.getInstansi() == castOther.getInstansi()) || (this
						.getInstansi() != null
						&& castOther.getInstansi() != null && this
						.getInstansi().equals(castOther.getInstansi())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNip() == null ? 0 : this.getNip().hashCode());
		result = 37 * result
				+ (getNama() == null ? 0 : this.getNama().hashCode());
		result = 37 * result
				+ (getInstansi() == null ? 0 : this.getInstansi().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
