package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import id.go.bkn.sscn.manager.Constanta;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DtDokumenAdm generated by hbm2java
 */
@Entity
@Table(name = "dt_dokumen_adm", catalog = Constanta.DB_CATALOG)
public class DtDokumenAdm implements java.io.Serializable {

	private DtDokumenAdmId id;
	private String nama;

	public DtDokumenAdm() {
	}

	public DtDokumenAdm(DtDokumenAdmId id, String nama) {
		this.id = id;
		this.nama = nama;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "instansi", column = @Column(name = "INSTANSI", nullable = false, length = 4)),
			@AttributeOverride(name = "kode", column = @Column(name = "KODE", nullable = false, length = 2)) })
	public DtDokumenAdmId getId() {
		return this.id;
	}

	public void setId(DtDokumenAdmId id) {
		this.id = id;
	}

	@Column(name = "NAMA", nullable = false, length = 100)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
