package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtHasil generated by hbm2java
 */
@Entity
@Table(name = "dt_hasil", catalog = "dbseleksicpns")
public class DtHasil implements java.io.Serializable {

	private String noPeserta;
	private Integer nilai01;
	private Integer nilai02;
	private Integer nilai03;
	private Integer total;
	private Integer nilaiTkb;
	private Integer nilaiLain;
	private Integer grandTotal;
	private String status;
	
	public DtHasil() {
	}

	public DtHasil(String noPeserta) {
		this.noPeserta = noPeserta;
	}

	public DtHasil(String noPeserta, Integer nilai01, Integer nilai02,
			Integer nilai03, Integer total, Integer nilaiTkb,
			Integer nilaiLain, Integer grandTotal) {
		this.noPeserta = noPeserta;
		this.nilai01 = nilai01;
		this.nilai02 = nilai02;
		this.nilai03 = nilai03;
		this.total = total;
		this.nilaiTkb = nilaiTkb;
		this.nilaiLain = nilaiLain;
		this.grandTotal = grandTotal;
	}

	@Id
	@Column(name = "NO_PESERTA", unique = true, nullable = false, length = 10)
	public String getNoPeserta() {
		return this.noPeserta;
	}

	public void setNoPeserta(String noPeserta) {
		this.noPeserta = noPeserta;
	}

	@Column(name = "NILAI_01")
	public Integer getNilai01() {
		return this.nilai01;
	}

	public void setNilai01(Integer nilai01) {
		this.nilai01 = nilai01;
	}

	@Column(name = "NILAI_02")
	public Integer getNilai02() {
		return this.nilai02;
	}

	public void setNilai02(Integer nilai02) {
		this.nilai02 = nilai02;
	}

	@Column(name = "NILAI_03")
	public Integer getNilai03() {
		return this.nilai03;
	}

	public void setNilai03(Integer nilai03) {
		this.nilai03 = nilai03;
	}

	@Column(name = "TOTAL")
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	@Column(name = "NILAI_TKB")
	public Integer getNilaiTkb() {
		return this.nilaiTkb;
	}

	public void setNilaiTkb(Integer nilaiTkb) {
		this.nilaiTkb = nilaiTkb;
	}

	@Column(name = "NILAI_LAIN")
	public Integer getNilaiLain() {
		return this.nilaiLain;
	}

	public void setNilaiLain(Integer nilaiLain) {
		this.nilaiLain = nilaiLain;
	}

	@Column(name = "GRAND_TOTAL")
	public Integer getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(Integer grandTotal) {
		this.grandTotal = grandTotal;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

}
