package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;
import id.go.bkn.sscn.manager.Constanta;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DtPengumuman generated by hbm2java
 */
@Entity
@Table(name = "dt_pengumuman", catalog = Constanta.DB_CATALOG)
public class DtPengumuman implements java.io.Serializable {

	private Integer id;
	private RefInstansi refInstansi;
	private byte[] berita;
	private String status;

	public DtPengumuman() {
	}

	public DtPengumuman(RefInstansi refInstansi, byte[] berita, String status) {
		this.refInstansi = refInstansi;
		this.berita = berita;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTANSI", nullable = false)
	public RefInstansi getRefInstansi() {
		return this.refInstansi;
	}

	public void setRefInstansi(RefInstansi refInstansi) {
		this.refInstansi = refInstansi;
	}

	@Column(name = "BERITA", nullable = false)
	public byte[] getBerita() {
		return this.berita;
	}

	public void setBerita(byte[] berita) {
		this.berita = berita;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
