package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import id.go.bkn.sscn.manager.Constanta;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefInstansi generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name = "instansi_id")
@Table(name = "periode_daftar", catalog = Constanta.DB_CATALOG)
public class PeriodeDaftar extends RefInstansi {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3178210195809712880L;

	private Date start;

	private Date end;

	private String username;

	public PeriodeDaftar() {
		super();
	}

	/**
	 * @return the start
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", columnDefinition = "DATETIME", nullable = true, length = 10)
	public Date getStart() {
		return start;
	}

	/**
	 * @param start
	 *            the start to set
	 */
	public void setStart(Date start) {
		this.start = start;
	}

	/**
	 * @return the end
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", columnDefinition = "DATETIME", nullable = true, length = 10)
	public Date getEnd() {
		return end;
	}

	/**
	 * @param end
	 *            the end to set
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * @return the username
	 */
	@Column(name = "username", nullable = true, length = 30)
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *            the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}
