package id.go.bkn.sscn.persistence.entities;

// Generated Aug 14, 2013 11:26:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * RefLokasi generated by hbm2java
 */
@Entity
@Table(name = "PROP_THK2", catalog = "dbseleksicpns")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class PropThk2 implements java.io.Serializable {

	private String kode;
	private String jenis;
	private String nama;
	

	public PropThk2() {
	}

	@Id
	@Column(name = "KD_PROP", unique = true, nullable = false, length = 2)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "nama", length = 150)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "jenis", length = 1)
	public String getJenis() {
		return this.jenis;
	}

	public void setJenis(String jenis) {
		this.jenis = jenis;
	}

}
