package id.go.bkn.sscn.persistence.entities;

// Generated Aug 12, 2013 12:44:57 PM by Hibernate Tools 3.4.0.CR1

import id.go.bkn.sscn.manager.Constanta;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * RefInstansi generated by hbm2java
 */
@Entity
@Table(name = "ref_instansi", catalog = Constanta.DB_CATALOG)
public class RefInstansi implements java.io.Serializable {

	private String kode;
	private String nama;
	private String status;
	private String jumlahMaxDaftar;
	private String pilihanLokasiTest;
	private Set<DtPengumuman> dtPengumumans = new HashSet<DtPengumuman>(0);
	private Set<MFormasi> MFormasis = new HashSet<MFormasi>(0);
	private Set<DtUser> dtUsers = new HashSet<DtUser>(0);
	

	public RefInstansi() {
	}

	public RefInstansi(String kode, String nama, String status, String jumlahMaxDaftar, String pilihanLokasiTest) {
		this.kode = kode;
		this.nama = nama;
		this.status = status;
		this.jumlahMaxDaftar = jumlahMaxDaftar;
		this.pilihanLokasiTest = pilihanLokasiTest;
	}

	public RefInstansi(String kode, String nama, String status,
			Set<DtPengumuman> dtPengumumans, Set<MFormasi> MFormasis,
			Set<DtUser> dtUsers, Set<RefPns> refPnses) {
		this.kode = kode;
		this.nama = nama;
		this.status = status;
		this.dtPengumumans = dtPengumumans;
		this.MFormasis = MFormasis;
		this.dtUsers = dtUsers;
//		this.refPnses = refPnses;
	}

	@Id
	@Column(name = "KODE", unique = true, nullable = false, length = 4)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "NAMA", nullable = false, length = 70)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "JUMLAH_MAX_DAFTAR", nullable = false, length = 1)
	public String getJumlahMaxDaftar() {
		return this.jumlahMaxDaftar;
	}

	public void setJumlahMaxDaftar(String jumlahMaxDaftar) {
		this.jumlahMaxDaftar = jumlahMaxDaftar;
	}

	
	@Column(name = "PILIHAN_LOKASI_TEST", nullable = false, length = 1)
	public String getPilihanLokasiTest() {
		return this.pilihanLokasiTest;
	}

	public void setPilihanLokasiTest(String pilihanLokasiTest) {
		this.pilihanLokasiTest = pilihanLokasiTest;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInstansi")
	public Set<DtPengumuman> getDtPengumumans() {
		return this.dtPengumumans;
	}

	public void setDtPengumumans(Set<DtPengumuman> dtPengumumans) {
		this.dtPengumumans = dtPengumumans;
	}

	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInstansi")
	public Set<MFormasi> getMFormasis() {
		return this.MFormasis;
	}

	public void setMFormasis(Set<MFormasi> MFormasis) {
		this.MFormasis = MFormasis;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInstansi")
	public Set<DtUser> getDtUsers() {
		return this.dtUsers;
	}

	public void setDtUsers(Set<DtUser> dtUsers) {
		this.dtUsers = dtUsers;
	}
	
//	@JsonIgnore
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refInstansi")
//	public Set<RefPns> getRefPnses() {
//		return this.refPnses;
//	}
//
//	public void setRefPnses(Set<RefPns> refPnses) {
//		this.refPnses = refPnses;
//	}

}
